#!/usr/bin/env python3

import csv
import os
import math
from datetime import datetime

import rclpy
from rclpy.node import Node
from rclpy.qos import (
    QoSProfile,
    ReliabilityPolicy,
    HistoryPolicy,
    DurabilityPolicy,
)

from geometry_msgs.msg import TwistStamped, WrenchStamped
from franka_msgs.msg import FrankaRobotState


class VelocityLogger(Node):

    def __init__(self):
        super().__init__('velocity_logger')

        # ============================================================
        # Topics
        # ============================================================

        self.lambda_topic = '/twist'
        self.franka_des_topic = '/cmd_vel_raw'

        # NEW:
        # Filtered/smoothed velocity BEFORE depth reduction
        self.pre_depth_topic = '/cmd_vel_filtered_pre_depth'

        self.franka_state_topic = (
            '/NS_1/franka_robot_state_broadcaster/robot_state'
        )

        # Force feedback generated by SmoothedCmdVel
        self.force_feedback_topic = '/cmd/force_feedback/wrench'

        # ============================================================
        # Latest Lambda velocity from /twist
        # ============================================================

        self.lambda_time = ''
        self.lambda_frame = ''

        self.lambda_x = 0.0
        self.lambda_y = 0.0
        self.lambda_z = 0.0

        self.lambda_ax = 0.0
        self.lambda_ay = 0.0
        self.lambda_az = 0.0

        # ============================================================
        # Latest Franka desired/raw velocity from /cmd_vel_raw
        # ============================================================

        self.franka_des_time = ''
        self.franka_des_frame = ''

        self.franka_des_x = 0.0
        self.franka_des_y = 0.0
        self.franka_des_z = 0.0

        self.franka_des_ax = 0.0
        self.franka_des_ay = 0.0
        self.franka_des_az = 0.0

        # ============================================================
        # NEW:
        # Filtered velocity BEFORE depth scaling
        # /cmd_vel_filtered_pre_depth
        # ============================================================

        self.pre_depth_time = ''
        self.pre_depth_frame = ''

        self.pre_depth_x = 0.0
        self.pre_depth_y = 0.0
        self.pre_depth_z = 0.0

        self.pre_depth_ax = 0.0
        self.pre_depth_ay = 0.0
        self.pre_depth_az = 0.0

        # ============================================================
        # Latest Franka measured velocity
        # robot_state.o_dp_ee_c
        # ============================================================

        self.franka_meas_time = ''
        self.franka_meas_frame = ''

        self.franka_meas_x = 0.0
        self.franka_meas_y = 0.0
        self.franka_meas_z = 0.0

        self.franka_meas_ax = 0.0
        self.franka_meas_ay = 0.0
        self.franka_meas_az = 0.0

        # ============================================================
        # Franka desired twist from robot_state.o_dp_ee_d
        # ============================================================

        self.franka_state_des_time = ''
        self.franka_state_des_frame = ''

        self.franka_state_des_x = 0.0
        self.franka_state_des_y = 0.0
        self.franka_state_des_z = 0.0

        self.franka_state_des_ax = 0.0
        self.franka_state_des_ay = 0.0
        self.franka_state_des_az = 0.0

        # ============================================================
        # Franka robot-state trajectory positions
        # ============================================================

        self.franka_state_time = ''
        self.franka_state_frame = ''

        # Measured EE pose: robot_state.o_t_ee
        self.franka_meas_px = ''
        self.franka_meas_py = ''
        self.franka_meas_pz = ''

        # Desired EE pose: robot_state.o_t_ee_d
        self.franka_des_px = ''
        self.franka_des_py = ''
        self.franka_des_pz = ''

        # Commanded EE pose: robot_state.o_t_ee_c
        self.franka_cmd_px = ''
        self.franka_cmd_py = ''
        self.franka_cmd_pz = ''

        # ============================================================
        # Force feedback
        # /cmd/force_feedback/wrench
        # ============================================================

        self.force_time = ''
        self.force_frame = ''

        self.force_x = 0.0
        self.force_y = 0.0
        self.force_z = 0.0

        self.torque_x = 0.0
        self.torque_y = 0.0
        self.torque_z = 0.0

        # Useful scalar for plotting force-feedback intensity
        self.force_norm = 0.0

        # ============================================================
        # CSV output
        # ============================================================

        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

        output_dir = os.path.expanduser('~/ros2_ws')
        os.makedirs(output_dir, exist_ok=True)

        self.csv_path = os.path.join(
            output_dir,
            f'lambda_franka_velocity_pose_force_log_{timestamp}.csv'
        )

        self.csv_file = open(
            self.csv_path,
            'w',
            newline=''
        )

        self.csv_writer = csv.writer(self.csv_file)

        # ============================================================
        # CSV header
        # ============================================================

        self.csv_writer.writerow([

            'log_time_sec',

            # --------------------------------------------------------
            # Lambda velocity
            # --------------------------------------------------------

            'lambda_msg_time_sec',
            'lambda_frame',

            'lambda_x',
            'lambda_y',
            'lambda_z',

            'lambda_ax',
            'lambda_ay',
            'lambda_az',

            # --------------------------------------------------------
            # Franka desired/raw velocity from /cmd_vel_raw
            # --------------------------------------------------------

            'franka_des_msg_time_sec',
            'franka_des_frame',

            'franka_des_x',
            'franka_des_y',
            'franka_des_z',

            'franka_des_ax',
            'franka_des_ay',
            'franka_des_az',

            # --------------------------------------------------------
            # NEW:
            # Filtered velocity BEFORE depth scaling
            # /cmd_vel_filtered_pre_depth
            # --------------------------------------------------------

            'pre_depth_msg_time_sec',
            'pre_depth_frame',

            'pre_depth_x',
            'pre_depth_y',
            'pre_depth_z',

            'pre_depth_ax',
            'pre_depth_ay',
            'pre_depth_az',

            # --------------------------------------------------------
            # Franka measured velocity
            # robot_state.o_dp_ee_c
            # --------------------------------------------------------

            'franka_meas_msg_time_sec',
            'franka_meas_frame',

            'franka_meas_x',
            'franka_meas_y',
            'franka_meas_z',

            'franka_meas_ax',
            'franka_meas_ay',
            'franka_meas_az',

            # --------------------------------------------------------
            # Franka desired twist from robot_state.o_dp_ee_d
            # --------------------------------------------------------

            'franka_state_des_msg_time_sec',
            'franka_state_des_frame',

            'franka_state_des_x',
            'franka_state_des_y',
            'franka_state_des_z',

            'franka_state_des_ax',
            'franka_state_des_ay',
            'franka_state_des_az',

            # --------------------------------------------------------
            # Robot state time/frame
            # --------------------------------------------------------

            'franka_state_time_sec',
            'franka_state_frame',

            # --------------------------------------------------------
            # EE trajectory positions
            # --------------------------------------------------------

            'franka_meas_px',
            'franka_meas_py',
            'franka_meas_pz',

            'franka_des_px',
            'franka_des_py',
            'franka_des_pz',

            'franka_cmd_px',
            'franka_cmd_py',
            'franka_cmd_pz',

            # --------------------------------------------------------
            # Force feedback
            # --------------------------------------------------------

            'force_feedback_msg_time_sec',
            'force_feedback_frame',

            'force_feedback_fx',
            'force_feedback_fy',
            'force_feedback_fz',

            'force_feedback_norm',

            'force_feedback_tx',
            'force_feedback_ty',
            'force_feedback_tz',
        ])

        self.csv_file.flush()

        # ============================================================
        # Subscribers
        # ============================================================

        self.lambda_sub = self.create_subscription(
            TwistStamped,
            self.lambda_topic,
            self.lambda_cb,
            10
        )

        self.franka_des_sub = self.create_subscription(
            TwistStamped,
            self.franka_des_topic,
            self.franka_des_cb,
            10
        )

        # ============================================================
        # NEW:
        # Pre-depth filtered velocity subscriber
        # ============================================================

        self.pre_depth_sub = self.create_subscription(
            TwistStamped,
            self.pre_depth_topic,
            self.pre_depth_cb,
            10
        )

        # ------------------------------------------------------------
        # Franka robot state QoS
        # ------------------------------------------------------------

        state_qos = QoSProfile(depth=20)
        state_qos.history = HistoryPolicy.KEEP_LAST
        state_qos.reliability = ReliabilityPolicy.RELIABLE
        state_qos.durability = DurabilityPolicy.VOLATILE

        self.franka_state_sub = self.create_subscription(
            FrankaRobotState,
            self.franka_state_topic,
            self.franka_state_cb,
            state_qos
        )

        # ------------------------------------------------------------
        # Force feedback subscriber
        # ------------------------------------------------------------

        self.force_feedback_sub = self.create_subscription(
            WrenchStamped,
            self.force_feedback_topic,
            self.force_feedback_cb,
            10
        )

        # ============================================================
        # Logging timer
        # 50 Hz = 0.02 s
        # ============================================================

        self.timer = self.create_timer(
            0.02,
            self.log_row
        )

        # ============================================================
        # Startup information
        # ============================================================

        self.get_logger().info(
            f'Logging Lambda velocity: {self.lambda_topic}'
        )

        self.get_logger().info(
            f'Logging Franka desired/raw velocity: {self.franka_des_topic}'
        )

        self.get_logger().info(
            f'Logging pre-depth filtered velocity: {self.pre_depth_topic}'
        )

        self.get_logger().info(
            f'Logging Franka robot state: {self.franka_state_topic}'
        )

        self.get_logger().info(
            f'Logging force feedback: {self.force_feedback_topic}'
        )

        self.get_logger().info(
            'Using robot_state.o_dp_ee_c as franka_meas velocity'
        )

        self.get_logger().info(
            f'CSV file: {self.csv_path}'
        )

    # ================================================================
    # Helper functions
    # ================================================================

    def stamp_to_sec(self, stamp):
        return (
            float(stamp.sec)
            + float(stamp.nanosec) * 1e-9
        )

    def now_sec(self):
        return (
            self.get_clock().now().nanoseconds
            * 1e-9
        )

    def read_twist_stamped(self, msg: TwistStamped):

        msg_time = self.stamp_to_sec(
            msg.header.stamp
        )

        return {
            'time': msg_time,
            'frame': msg.header.frame_id,

            'x': msg.twist.linear.x,
            'y': msg.twist.linear.y,
            'z': msg.twist.linear.z,

            'ax': msg.twist.angular.x,
            'ay': msg.twist.angular.y,
            'az': msg.twist.angular.z,
        }

    def read_twist_stamped_with_fallback(
        self,
        msg: TwistStamped,
        fallback_time,
        fallback_frame
    ):

        msg_time = self.stamp_to_sec(
            msg.header.stamp
        )

        if msg_time <= 0.0:
            msg_time = fallback_time

        frame = msg.header.frame_id

        if frame == '':
            frame = fallback_frame

        return {
            'time': msg_time,
            'frame': frame,

            'x': msg.twist.linear.x,
            'y': msg.twist.linear.y,
            'z': msg.twist.linear.z,

            'ax': msg.twist.angular.x,
            'ay': msg.twist.angular.y,
            'az': msg.twist.angular.z,
        }

    # ================================================================
    # Lambda callback
    # ================================================================

    def lambda_cb(self, msg: TwistStamped):

        data = self.read_twist_stamped(msg)

        self.lambda_time = data['time']
        self.lambda_frame = data['frame']

        self.lambda_x = data['x']
        self.lambda_y = data['y']
        self.lambda_z = data['z']

        self.lambda_ax = data['ax']
        self.lambda_ay = data['ay']
        self.lambda_az = data['az']

    # ================================================================
    # Franka desired/raw velocity callback
    # ================================================================

    def franka_des_cb(self, msg: TwistStamped):

        data = self.read_twist_stamped(msg)

        self.franka_des_time = data['time']
        self.franka_des_frame = data['frame']

        self.franka_des_x = data['x']
        self.franka_des_y = data['y']
        self.franka_des_z = data['z']

        self.franka_des_ax = data['ax']
        self.franka_des_ay = data['ay']
        self.franka_des_az = data['az']

    # ================================================================
    # NEW:
    # Pre-depth filtered velocity callback
    # ================================================================

    def pre_depth_cb(self, msg: TwistStamped):

        data = self.read_twist_stamped(msg)

        self.pre_depth_time = data['time']
        self.pre_depth_frame = data['frame']

        self.pre_depth_x = data['x']
        self.pre_depth_y = data['y']
        self.pre_depth_z = data['z']

        self.pre_depth_ax = data['ax']
        self.pre_depth_ay = data['ay']
        self.pre_depth_az = data['az']

    # ================================================================
    # FORCE FEEDBACK CALLBACK
    # ================================================================

    def force_feedback_cb(self, msg: WrenchStamped):

        # Message timestamp
        msg_time = self.stamp_to_sec(
            msg.header.stamp
        )

        # Fallback in case timestamp is zero
        if msg_time <= 0.0:
            msg_time = self.now_sec()

        self.force_time = msg_time
        self.force_frame = msg.header.frame_id

        # ------------------------------------------------------------
        # Linear force [N]
        # ------------------------------------------------------------

        self.force_x = float(
            msg.wrench.force.x
        )

        self.force_y = float(
            msg.wrench.force.y
        )

        self.force_z = float(
            msg.wrench.force.z
        )

        # ------------------------------------------------------------
        # Torque [N m]
        # ------------------------------------------------------------

        self.torque_x = float(
            msg.wrench.torque.x
        )

        self.torque_y = float(
            msg.wrench.torque.y
        )

        self.torque_z = float(
            msg.wrench.torque.z
        )

        # ------------------------------------------------------------
        # Resultant force magnitude
        #
        # |F| = sqrt(Fx^2 + Fy^2 + Fz^2)
        # ------------------------------------------------------------

        self.force_norm = math.sqrt(
            self.force_x ** 2
            + self.force_y ** 2
            + self.force_z ** 2
        )

    # ================================================================
    # Franka robot state callback
    # ================================================================

    def franka_state_cb(
        self,
        msg: FrankaRobotState
    ):

        # ------------------------------------------------------------
        # Robot state timestamp
        # ------------------------------------------------------------

        state_time = self.stamp_to_sec(
            msg.header.stamp
        )

        if state_time <= 0.0:
            try:
                state_time = float(msg.time)
            except Exception:
                state_time = self.now_sec()

        if state_time <= 0.0:
            state_time = self.now_sec()

        state_frame = msg.header.frame_id

        self.franka_state_time = state_time
        self.franka_state_frame = state_frame

        # ------------------------------------------------------------
        # Franka measured velocity
        # robot_state.o_dp_ee_c
        # ------------------------------------------------------------

        meas_twist = (
            self.read_twist_stamped_with_fallback(
                msg.o_dp_ee_c,
                fallback_time=state_time,
                fallback_frame=state_frame
            )
        )

        self.franka_meas_time = meas_twist['time']
        self.franka_meas_frame = meas_twist['frame']

        self.franka_meas_x = meas_twist['x']
        self.franka_meas_y = meas_twist['y']
        self.franka_meas_z = meas_twist['z']

        self.franka_meas_ax = meas_twist['ax']
        self.franka_meas_ay = meas_twist['ay']
        self.franka_meas_az = meas_twist['az']

        # ------------------------------------------------------------
        # Franka desired twist
        # robot_state.o_dp_ee_d
        # ------------------------------------------------------------

        state_des_twist = (
            self.read_twist_stamped_with_fallback(
                msg.o_dp_ee_d,
                fallback_time=state_time,
                fallback_frame=state_frame
            )
        )

        self.franka_state_des_time = (
            state_des_twist['time']
        )

        self.franka_state_des_frame = (
            state_des_twist['frame']
        )

        self.franka_state_des_x = (
            state_des_twist['x']
        )

        self.franka_state_des_y = (
            state_des_twist['y']
        )

        self.franka_state_des_z = (
            state_des_twist['z']
        )

        self.franka_state_des_ax = (
            state_des_twist['ax']
        )

        self.franka_state_des_ay = (
            state_des_twist['ay']
        )

        self.franka_state_des_az = (
            state_des_twist['az']
        )

        # ------------------------------------------------------------
        # Trajectory positions
        # ------------------------------------------------------------

        # Measured EE position: o_t_ee
        self.franka_meas_px = (
            msg.o_t_ee.pose.position.x
        )

        self.franka_meas_py = (
            msg.o_t_ee.pose.position.y
        )

        self.franka_meas_pz = (
            msg.o_t_ee.pose.position.z
        )

        # Desired EE position: o_t_ee_d
        self.franka_des_px = (
            msg.o_t_ee_d.pose.position.x
        )

        self.franka_des_py = (
            msg.o_t_ee_d.pose.position.y
        )

        self.franka_des_pz = (
            msg.o_t_ee_d.pose.position.z
        )

        # Commanded EE position: o_t_ee_c
        self.franka_cmd_px = (
            msg.o_t_ee_c.pose.position.x
        )

        self.franka_cmd_py = (
            msg.o_t_ee_c.pose.position.y
        )

        self.franka_cmd_pz = (
            msg.o_t_ee_c.pose.position.z
        )

    # ================================================================
    # CSV logging
    # ================================================================

    def log_row(self):

        now = self.now_sec()

        self.csv_writer.writerow([

            now,

            # --------------------------------------------------------
            # Lambda velocity
            # --------------------------------------------------------

            self.lambda_time,
            self.lambda_frame,

            self.lambda_x,
            self.lambda_y,
            self.lambda_z,

            self.lambda_ax,
            self.lambda_ay,
            self.lambda_az,

            # --------------------------------------------------------
            # Franka desired/raw velocity
            # /cmd_vel_raw
            # --------------------------------------------------------

            self.franka_des_time,
            self.franka_des_frame,

            self.franka_des_x,
            self.franka_des_y,
            self.franka_des_z,

            self.franka_des_ax,
            self.franka_des_ay,
            self.franka_des_az,

            # --------------------------------------------------------
            # NEW:
            # Pre-depth filtered velocity
            # /cmd_vel_filtered_pre_depth
            # --------------------------------------------------------

            self.pre_depth_time,
            self.pre_depth_frame,

            self.pre_depth_x,
            self.pre_depth_y,
            self.pre_depth_z,

            self.pre_depth_ax,
            self.pre_depth_ay,
            self.pre_depth_az,

            # --------------------------------------------------------
            # Franka measured velocity
            # --------------------------------------------------------

            self.franka_meas_time,
            self.franka_meas_frame,

            self.franka_meas_x,
            self.franka_meas_y,
            self.franka_meas_z,

            self.franka_meas_ax,
            self.franka_meas_ay,
            self.franka_meas_az,

            # --------------------------------------------------------
            # Franka robot-state desired velocity
            # --------------------------------------------------------

            self.franka_state_des_time,
            self.franka_state_des_frame,

            self.franka_state_des_x,
            self.franka_state_des_y,
            self.franka_state_des_z,

            self.franka_state_des_ax,
            self.franka_state_des_ay,
            self.franka_state_des_az,

            # --------------------------------------------------------
            # Robot state
            # --------------------------------------------------------

            self.franka_state_time,
            self.franka_state_frame,

            # --------------------------------------------------------
            # EE trajectory
            # --------------------------------------------------------

            self.franka_meas_px,
            self.franka_meas_py,
            self.franka_meas_pz,

            self.franka_des_px,
            self.franka_des_py,
            self.franka_des_pz,

            self.franka_cmd_px,
            self.franka_cmd_py,
            self.franka_cmd_pz,

            # --------------------------------------------------------
            # FORCE FEEDBACK
            # --------------------------------------------------------

            self.force_time,
            self.force_frame,

            self.force_x,
            self.force_y,
            self.force_z,

            self.force_norm,

            self.torque_x,
            self.torque_y,
            self.torque_z,
        ])

        self.csv_file.flush()

    # ================================================================
    # Shutdown
    # ================================================================

    def destroy_node(self):

        try:
            self.csv_file.flush()
            self.csv_file.close()

        except Exception:
            pass

        super().destroy_node()


# ====================================================================
# Main
# ====================================================================

def main():

    rclpy.init()

    node = VelocityLogger()

    try:
        rclpy.spin(node)

    except KeyboardInterrupt:
        pass

    finally:

        node.destroy_node()

        if rclpy.ok():
            rclpy.shutdown()


if __name__ == '__main__':
    main()
